name: Django CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: drf_lms

    - name: Run tests
      run: python manage.py test
      working-directory: drf_lms

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/alexey-1408/Django_RDF
          git pull origin main
          source venv/bin/activate
          pip install -r drf_lms/requirements.txt
          cd drf_lms
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
